gvs/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from adminplus.sites import AdminSitePlus

admin.site = AdminSitePlus()
admin.sites.site = admin.site
admin.autodiscover()

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^logbook/', include('logbook.urls')),
]

logbook/urls.py
from django.conf.urls import url
from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm, password_reset_complete 
from . import views

app_name = 'logbook'
urlpatterns = [
    url(r'^$', views.indexView, name='index'),
    url(r'^faq/$', views.faqView, name='faq'),
    url(r'^accounts/signup/$', views.signupView, name='signup'),
    url(r'^activate/(?P<key>.+)$', views.activation, name = 'activate'),
    url(r'^new-activation-link/(?P<user_id>[0-9]+)/$', views.new_activation_link, name = 'new_activation_link'),
    url(r'^accounts/signup/supervisor/$', views.supervisorSignupView, name='super_signup'),
    url(r'^accounts/login/$', views.loginView, name='login'),
    url(r'^accounts/logout/$', views.logoutView, name='logout'),
    url(r'^accounts/password_reset/$', password_reset, {'post_reset_redirect':'/logbook/accounts/password_reset/done'}, name='password_reset'),
    url(r'^accounts/password_reset/done/$', password_reset_done, name='password_reset_done'),
    url(r'^accounts/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        password_reset_confirm, {'post_reset_redirect':'/logbook/accounts/reset/done/'},
        name='password_reset_confirm'),
    url(r'^accounts/reset/done/$', password_reset_complete, name='password_reset_complete'),
    url(r'^profile/$', views.profileView, name='profile'),
    url(r'^delete_user/$', views.deleteUserView, name='delete_user'),
    url(r'^edit_names/$', views.editNamesView, name='edit_names'),
    url(r'^b/$', views.booksView, name='list'),
    url(r'^b/load_book/$', views.loadBookView, name='load_book'),
    url(r'^b/edit_book/$', views.editLogBookView, name='edit_book'),
    url(r'b/update_approvals/$', views.updateHoursList, name='update_hours'),
    url(r'^b/(?P<pk>[0-9]+)/$',views.logEntryView, name='view'),
    url(r'^b/(?P<pk>[0-9]+)/create_supervisor/$',views.createTempSupervisorView, name='create_super'),
    url(r'b/(?P<pk>[0-9]+)/add_entry', views.addLogEntryView, name='add_entry'),
    url(r'b/load_entry/$', views.loadEntryView, name='load_entry'),
    url(r'b/(?P<pk>[0-9]+)/edit_entry/$', views.editLogEntryView, name='edit_entry'),
    url(r'^search/$', views.searchBarView, name='search_bar'),
    ]

logbook/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings

import datetime

class LBUser(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.PROTECT)
    activation_key = models.CharField(max_length=64)
    key_expires = models.DateTimeField(default=datetime.datetime.now()+datetime.timedelta(days=7))
    def __str__(self):
        return str(self.user)

class Organisation(models.Model):
    name = models.CharField(max_length=200)
    code = models.CharField(max_length=8, blank=True, default=None)
    def __str__(self):
        return str(self.name)

class Supervisor(models.Model):
    email = models.EmailField(primary_key=True)
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, default=None)
    validated = models.BooleanField(default=False)
    # organisation is nullable because some supervisors might not belong to an organisation, or haven't been assigned one yet
    organisation = models.ForeignKey(Organisation, on_delete=models.SET_NULL, null=True, default=None)
    def __str__(self):
        return str(self.email)

class Category(models.Model):
    name = models.CharField(max_length=200)
    def __str__(self):
        return str(self.name)

class LogBook(models.Model):
    user = models.ForeignKey(LBUser, on_delete=models.PROTECT)
    organisation = models.ForeignKey(Organisation, on_delete=models.SET_NULL, null=True, default=None )
    category = models.ForeignKey(Category, on_delete=models.PROTECT, null=True, default=None)
    name = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    finalised = models.BooleanField(default=False)
    active = models.BooleanField(default=True)
    exported = models.BooleanField(default=False)
    
    def __str__(self):
        return str(self.user) + " - " + self.name
    readonly_fields = ('created_at','updated_at',)

class LogEntry(models.Model):
    book = models.ForeignKey(LogBook, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    supervisor = models.ForeignKey(Supervisor, on_delete=models.SET_NULL, null=True)
    start = models.DateTimeField('task start')
    end = models.DateTimeField('task end')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    UNAPPROVED = 'Unapproved'
    PENDING = 'Pending'
    APPROVED = 'Approved'
    STATUS_CHOICES = (
        # Has not been submitted for approval or was denied (use last modified time).
            (UNAPPROVED, 'Unapproved'),
            (PENDING, 'Pending'), # Awaiting approval.
            (APPROVED, 'Approved'), # Supervisor has approved the log entry.
        )
    status = models.CharField(choices = STATUS_CHOICES, max_length = 15, default = UNAPPROVED)

    def save(self, *args, **kwargs):
        if not self.book.finalised == True or not self.book.active == False:
            super(LogEntry, self).save(*args, **kwargs)
    
    def __str__(self):
        return str(self.book) + " - " + self.name
    readonly_fields = ('created_at','updated_at',)

logbook/views.py
# Database
from django.db import transaction
from django.db.models import ExpressionWrapper, F, Count, Sum, fields, Q

# User authentication
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User, Group

#Redirect
from django.shortcuts import render, redirect,get_object_or_404
from django.http import HttpResponseNotFound, HttpResponseForbidden, HttpResponse
from django.urls import reverse

#Logbook Project
from .forms import *
from .admin import *
from django.conf import settings

#General
from django.template import RequestContext
from django.utils.crypto import get_random_string
from django.core import serializers
from django.core.serializers.json import DjangoJSONEncoder
from django.utils import timezone
import datetime
import hashlib
import json
import string


#Checks to see if the user passed to the function is a supervisor.
def is_supervisor(user):
    return user.groups.filter(name='LBSupervisor').exists()

#Checks to see if the user passed to the function is a student.
def is_lbuser(user):
    return user.groups.filter(name='LBStudent').exists()

#Creates headers which can be sorted for the tables in log books and log entries.
def makeHeaders(unformattedHeaderNames, currentOrder):
    '''
    Makes the headers and ordering urls for a list of models
    '''
    headerNames = [string.capwords(s.replace('_', ' ')) for s in unformattedHeaderNames]
    headerOrders = []
    # work out the urls for sorting when clinking on headers
    for i in range(1, len(headerNames)+1):
        newOrder = []
        # toggle between ascending and descending
        newOrder.append('-'+str(i) if str(i) in currentOrder else str(i))
        for n in currentOrder:
        # if previously sorted by this header don't include it twice
            if not str(i) in n:
                newOrder.append(n)
        headerOrders.append('.'.join(newOrder))
    return zip(headerNames, headerOrders)

def orderModels(order, unformattedHeaderNames, models):
    '''
    Orders models for a list of models
    '''
    if order == models:
        return
    sortArgs = []
    for i in order:
        if i[0] == '-':
            sortArgs.append('-'+unformattedHeaderNames[int(i[1])-1])
        else:
            sortArgs.append(unformattedHeaderNames[int(i[0])-1])
    return models.order_by(*sortArgs)

#Controls the actions when a user submits a POST on a form containing a number
# of elements in a table.
def modelActions(request, model, permissionCheck):
    action = request.POST['selectedAction']
    modelIDs = request.POST.getlist('model_selected')
    #Delete log book/s or entry/s
    if action == 'delete':
        for i in modelIDs:
            try:
                m = model.objects.get(id=i)
            except model.DoesNotExist:
                pass
            # ensure user has permission
            if permissionCheck(request.user, m, 'delete'):
                m.delete()
    #Submit log book/entries to be approved
    if action == 'submit':
        for i in modelIDs:
            try:
                m = model.objects.get(id=i)
            except model.DoesNotExist:
                pass
            if permissionCheck(request.user, m, 'submit'):
                try:
                    if m.status == 'Unapproved':
                        m.status = 'Pending'
                        m.save()
                # Then it is a logbook (surely a 'safer' way to do this?)
                except:
                    logentries = LogEntry.objects.filter(book=m.id)
                    for log in logentries:
                        if log.status == 'Unapproved':
                            log.status = 'Pending'
                            log.save()
    #Finalise Log Book/s
    if action == 'finalise':
        for i in modelIDs:
            try:
                m = model.objects.get(id=i)
            except model.DoesNotExist:
                pass
            
            if permissionCheck(request.user, m, 'finalise'):
                m.finalised = True
                m.save()
                    
    #Supervisor approve log entry
    if action == 'approve':
        for i in modelIDs:
            try:
                m = model.objects.get(id=i)
            except model.DoesNotExist:
                pass
            if permissionCheck(request.user, m, 'approve'):
                if m.status == 'Pending':
                    m.status = 'Approved'
                    m.save()
    #Supervisor decline log entry
    if action == 'decline':
        for i in modelIDs:
            try:
                m = model.objects.get(id=i)
            except model.DoesNotExist:
                pass
            if permissionCheck(request.user, m, 'decline'):
                if m.status == 'Pending':
                    m.status = 'Unapproved'
                    m.save()

"""
Below are checks to ensure the log book or the log entry can be interacted with
in the selected selected way by the user, if not it will return False.
"""
def logbookPermissionCheck(user, logbook, action):
    user = LBUser.objects.get(user=user)
    if action == 'delete':
        # Don't delete the book if it contains approved or pending entries
        entries = LogEntry.objects.filter(book=logbook, status__in=['Approved','Pending'])
        if len(entries) == 0:
            return True
    elif action == 'finalise':
        if hasAllApproved(logbook) == True:
            return True
        else:
            return False
    elif action == 'edit':
        if logbook.finalised == True or logbook.active == False:
            return False
        else:
            return True
    return user == logbook.user

def logentryPermissionCheck(user, logentry, action):
    if logentry.book.finalised == True:
        return False
    else:
        user = LBUser.objects.get(user=user)
        if user == logentry.book.user:
            if action == 'delete':
                # don't delete an approved entry
                if not logentry.status == 'Approved':
                    return True
        
            elif action == 'submit':
                return True

            elif action == 'edit':
                if not logentry.status == 'Approved':
                    return True
                else: return False
                
            return False
    
"""
A specific check for supervisors
"""
def approvePermissionCheck(user, logentry, action):
    user = Supervisor.objects.get(user=user)
    #limit actions to only allowed ones.
    if action == 'approve':
        return True
    if action == 'decline':
        return True
    return False
        
"""
Loads the 'front page' only if a user currently has an active session, otherwise
redirects to the login page.
"""
def indexView(request):
    if not request.user.is_authenticated():
        return redirect('logbook:login')
    #Checks if a user is a supervisor
    elif is_supervisor(request.user):
        is_super = True
        return render(request, 'index.html', {'is_super':is_super})
    #Checks to see if user is a student.
    elif is_lbuser(request.user):
        is_super = False
        return render(request, 'index.html', {'is_super':is_super})
    #If the user has not been assigned a user group this will show an error,
    #and tell user to talk to guild volunteering to check account settings.
    else:
        return render(request, 'error.html', {})

"""
Simple view to show the Frequently Asked Questions page
"""
def faqView(request):
    return render(request, 'faq.html', {})

#Function which checks to see if a specific logbook has all its logentries approved,
#this is a function which is ready to be finalised by the user.
def hasAllApproved(logbook):
    entries = LogEntry.objects.filter(book = logbook.id)
    if len(entries) == 0:
        return False
    for entry in entries:
        if entry.status == 'Unapproved' or entry.status == 'Pending':
            return False
    return True

@login_required
def loadBookView(request):
    if request.is_ajax():
        if request.method == "GET":
            
            book_id = request.GET['book_id']
            logbook = LogBook.objects.get(id=book_id)
            #object
            output = {'name':logbook.name,'category':logbook.category.name}
            #response
            output = json.dumps(output, cls=DjangoJSONEncoder)
            return HttpResponse(output, content_type='application/json')
        
        else:
            return HttpResponseForbidden()
        
    else:
        return HttpResponseForbidden()

@login_required
def editLogBookView(request):
    if request.method == "POST":
        edit_form = EditLogBookForm(request.POST)
        
        if edit_form.is_valid():
            name_form = edit_form.cleaned_data['name']
            category_form = edit_form.cleaned_data['category']
            
            book_id = request.POST['book_id']
            logbook = LogBook.objects.get(id=book_id)

            if logbookPermissionCheck(request.user, logbook, 'edit'):
                logbook.name = name_form
                logbook.category = category_form

                logbook.save()
                return redirect('logbook:list')
            else:
                return redirect('logbook:list')
        else:
            return HttpResponseForbidden()
            
    else:
        return HttpResponseForbidden()

"""
View which handles the request from a user to add a logbook.
"""
@login_required
def addLogBookView(request):
    if request.method == "POST":
        form = LogBookForm(request.POST)
        if form.is_valid():
            logbook = LogBook.objects.create(name=form.cleaned_data['bookName'],
                                             organisation=form.cleaned_data['bookOrganisation'],
                                             category=form.cleaned_data['bookCategory'],

logbook/templates/activation.html
<html lang="en">

{% extends 'base.html' %}

{% block titleblock %}Activated Account{% endblock %}

{% block bodyblock %}
<div class="col-sm-8 col-sm-offset-4 col-md-10 col-md-offset-2 main">
    {% if activation_expired %}
    <h1 class="page-header">Your activation link has expired!</h1>
    <p>
        Click <a href="{% url 'logbook:new_activation_link' user_id %}">here</a> to resend your activation link.
    </p>
    {% elif isActive %}
        {% if request.user.is_authenticated %}
        <h1 class="page-header">You are already logged in!</h1>
        <p>
            Click <a href="{% url 'logbook:index' %}">here</a> to go home.
        </p>
        {% else %}
        <h1 class="page-header">Your account is already activated!</h1>
        <p>
            Click <a href="{% url 'logbook:login' %}">here</a> to login.
        </p>
        {% endif %}
    {% else %}
    <h1 class="page-header">Your account has been activated!</h1>
    <p>
        Click <a href="{% url 'logbook:login' %}">here</a> to login.
    </p>
    {% endif %}
</div>
{% endblock %}

logbook/templates/base.html
<html lang="en">

{% load static %}

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href=" http://getbootstrap.com/favicon.ico">

    <title>{% block titleblock %}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    
    <!-- Bootstrap CSS CDN -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!-- BootStrap CSS LOCAL -->
    <!-- Custom styles -->
    <link href="{% static "css/dashboard.css" %}" rel="stylesheet">
    <!-- Javascript + dependencies -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <!-- Bootstrap JS CDN -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <!-- Dependencies of date-time widget LOCAL -->
    {% block date_timeblock %}{% endblock %}
    
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="http://getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>
    
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="http://getbootstrap.com/assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

    <script src=" http://getbootstrap.com/assets/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    {% block headerblock %}{% endblock %}
	<style>{% block styleblock %}{% endblock %}</style>
    {{ form.media }}
</head>

<body>
    <div class="wrapper">
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" id="brand" href="{% url 'logbook:index' %}"><span class="glyphicon glyphicon-home hidden-xs" aria-hidden="true"></span> Guild Volunteering System</a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li class="visible-xs"><a href="{% url 'logbook:index' %}"><span class="glyphicon glyphicon-home" aria-hidden="true"></span> Home</a></li>
                        <li class="hidden-xs"><a href="{% url 'logbook:faq' %}">FAQ</a></li>
                        <li class="visible-xs"><a href="{% url 'logbook:faq' %}"><span class="glyphicon glyphicon-question-sign" aria-hidden="true"></span> FAQ</a></li>
                        {% if user.is_authenticated %}
                        <li class="hidden-xs"><a href="{% url 'logbook:profile' %}">{{ user.username }}</a></li>
                        <li class="visible-xs"><a href="{% url 'logbook:profile' %}"><span class="glyphicon glyphicon-user" aria-hidden="true"></span> {{ user.username }}</a></li>
                        <li class="hidden-xs"><a href="{% url 'logbook:logout' %}">Logout</a></li>
                        <li class="visible-xs"><a href="{% url 'logbook:logout' %}"><span class="glyphicon glyphicon-log-out" aria-hidden="true"></span> Logout</a></li>
                        {% else %}
                        <li class="hidden-xs"><a href="{% url 'logbook:login' %}">Login</a></li>
                        <li class="visible-xs"><a href="{% url 'logbook:login' %}"><span class="glyphicon glyphicon-log-in" aria-hidden='true'></span> Login</a></li>
                        <li><a href="{% url 'logbook:signup' %}">Sign Up!</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>

        <div class="container-fluid">
            <div class="row">
                {% block sideblock %}{% endblock %}
                {% block bodyblock %}{% endblock %}
            </div>
        </div>
    </div>
    <footer class="footer hidden-xs">
        <div class="container">
            <div class="row">
                <div class="col-sm-2 col-md-2 col-lg-2" style="margin-bottom:15px; margin-top:15px;">
                    <a><img src="{% static "images/footer-logo-1.png" %}" /></a>
                </div>
                <div class="col-sm-10 col-md-10 col-lg-10 text-right" style="margin-top:60px;">
                    <div class="row align-right">
                        <ul>
                            <li>
                                <a href="http://www.uwastudentguild.com/" target="_blank">UWA STUDENT GUILD</a>
                            </li>
                            <li>
                                <a href="http://websiteindevelopment.biz/wordpress/volunteering/">HOME</a>
                            </li>
                            <li>
                                <a href="http://websiteindevelopment.biz/wordpress/volunteering/">NEWSLETTER</a>
                            </li>
                            <li>
                                <a href="http://websiteindevelopment.biz/wordpress/volunteering/about/">ABOUT</a>
                            </li>
                            <li>
                                <a href="http://websiteindevelopment.biz/wordpress/volunteering/volunteer-opportunities/">VOLUNTEER OPPORTUNITIES</a>
                            </li>
                            <li>
                                <a href="http://websiteindevelopment.biz/wordpress/volunteering/partners/">PARTNERS</a>
                            </li>
                            <li>
                                <a href="http://websiteindevelopment.biz/wordpress/volunteering/support/">SUPPORT</a>
                            </li>
                            <li style="">
                                <a href="http://websiteindevelopment.biz/wordpress/volunteering/contact/">CONTACT</a>
                            </li>
                        </ul>
                    </div>
                    <div class="row align-right">
                        <div class="social-footer">
                            <a target="_blank" title="Facebook" href="http://www.facebook.com/GuildVolunteering"><img src="{% static "images/facebook-logo.png" %}" border="0" width="32" alt="Facebook" style="margin: 2px; opacity: 1;"></a>
                            <a target="_blank" title="Twitter" href="http://twitter.com/GuildVolunteer"><img src="{% static "images/twitter-logo.png" %}" border="0" width="32" alt="Twitter" style="margin: 2px; opacity: 1;"></a>
                            <a target="_blank" title="Instagram" href="http://www.instagram.com/guildvolunteeringuwa/"><img src="{% static "images/instagram-logo.png" %}" border="0" width="32" alt="Instagram" style="margin: 2px; opacity: 1;"></a>
                            <a target="_blank" title="Email" target="_top" href="mailto:volunteering@guild.uwa.edu.au"><img src="{% static "images/envelope-logo.png" %}" border="0" width="36px" height="38px" alt="Email" style="margin: 2px; opacity: 1;"></a>
                            <form class="navbar-form navbar-right" style="padding-left:30px;" id="searchForm" method="post" action="{% url 'logbook:search_bar' %}">    
                                <div class="form-group has-feedback">
                                    {% csrf_token %}
                                    {{ search_bar.as_p }}
                                    <a style="color: #000000">
                                        <i class="glyphicon glyphicon-search form-control-feedback"></i>
                                    </a>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12 col-md-12 col-lg-12" style="padding-top: 20px;">
                    <div class="copyright-content"><p>COPYRIGHT © 2017 UWA STUDENT GUILD | ABN 39 156 317 391</p></div>
                </div>
            </div>
        </div>
        {% block footerblock %}{% endblock %}
        <!-- {{creators}} -->
    </footer>
</body>
</html>

logbook/templates/error.html
<html lang="en">

{% extends 'base.html' %}

{% block titleblock %} {{ title }} {% endblock %}

{% block bodyblock %}
<div class="col-sm-8 col-sm-offset-2 col-md-10 col-md-offset-1 text-center main">
    <h1 class="page-header">Serious Error Has Occured</h1>
    <p>
        Please contact UWA Guild Volunteering in regards to issues with this account's settings.
    </p>
</div>
{% endblock %}

logbook/templates/form.html
<html lang="en">

{% extends 'base.html' %}

{% block titleblock %} {{ title }} {% endblock %}

{% block sideblock %}
<div class="col-sm-4 col-md-2 sidebar" id="sidebar">
    <ul class="nav" id="menu" style="display: inline-block;">
        <li><a href="{{backUrl}}">Back</a></li>
    </ul>
</div>
{% endblock %}

{% block bodyblock %}
<div class="col-sm-8 col-sm-offset-4 col-md-10 col-md-offset-2 main">
    <h1 class="page-header">{{title}}</h1>
    <form action="." method="post">
        {% csrf_token %} {{ form.as_p}}
        <button class="btn" type="submit" value="Submit">Create</button>
    </form>
</div>
{% endblock %}

logbook/templates/index.html
<html lang="en">

{% extends 'base.html' %}

{% load static %}

{% block titleblock %}Welcome{% endblock %}

{% block bodyblock %}
<div style="display: inline-block; vertical-align: middle; float: none; padding-top: 6%; padding-bottom: 6%;" class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3 text-center main" id="main">
    <h1 class="page-header" style="text-align: center;">Welcome to the Guild Volunteering System</h1>
    <div class="row placeholders">
        <div class="col-xs-4 col-sm-4 col-md-4">
            <a href="{% url 'logbook:list' %}">
                <img src="{% static "images/log_icon.png" %}" class="img-responsive" width="100%" height="100%" alt="Manage Your Logs">
            </a>
            {% if is_super %}
            <h4><a href="{% url 'logbook:list' %}">Approve Volunteer Hours</a></h4>
            <span class="text-muted hidden-xs">Approve or unapprove volunteer's logged hours you have supervised.</span>
            {% else %}
            <a href="{% url 'logbook:list' %}"><h4>Manage Your Log Books</h4></a>
            <span class="text-muted hidden-xs">Add entries to your log books and get them approved by your supervisor.</span>
            {% endif %}
        </div>
        <div class="col-xs-4 col-xs-offset-0 col-sm-4 col-sm-offset-0 col-md-4">
            <a href="{% url 'logbook:profile' %}">
                <img src="{% static "images/profile_icon.png" %}" class="img-responsive" width="100%" height="100%" alt="Manage Your Log Books">
            </a>
            <a href="{% url 'logbook:profile' %}">
                <h4>View Your Profile</h4>
            </a>
            <span class="text-muted hidden-xs">Change your account details, view stats, and see what badges you've earnt.</span>
        </div>
        <div class="col-xs-4 col-xs-offset-0 col-sm-4 col-sm-offset-0 col-md-4">
            <a href="{% url 'logbook:faq' %}">
                <img src="{% static "images/faq_icon.png" %}" class="img-responsive" width="100%" height="100%" alt="Manage Your Log Books">
            </a>
            <a href="{% url 'logbook:faq' %}">
                <h4>FAQ</h4>
            </a>
            <span class="text-muted hidden-xs">View a guide on using this site, and any frequently asked questions that may help you.</span>
        </div>
    </div>
</div>
{% endblock %}

logbook/templates/login.html
<html lang="en">

{% extends 'base.html' %}

{% load static %}

{% block titleblock %}Login{% endblock %}

{% block bodyblock %}
<link href="{% static "css/signin.css" %}" rel="stylesheet">

<div class="col-lg-8 col-lg-offset-2">
    <form class="form-signin" role="form" method="post" action=".">
        {% csrf_token %}
        <h2 class="form-signin-heading">Please Sign In</h2> 
        {{ loginForm.as_p }}
        <button class="btn btn-lg btn-primary btn-block" type="submit" value="Submit">Sign in</button>
        <p>
        <h4>Don't have an account? <a href="{% url 'logbook:signup' %}">Register</a></h4>
        <h4>Forgot your password? <a href="{% url 'logbook:password_reset' %}">Reset Password</a></h4>
        </p>
    </form>
</div>
{% endblock %}

logbook/templates/signup.html
<html lang="en">

{% extends 'base.html' %}

{% load static %}

{% block titleblock %}Register!{% endblock %}

{% block bodyblock %}
<link href="{% static "css/signin.css" %}" rel="stylesheet">
<div class="col-sm-3 col-sm-offset-4 col-lg-3 col-lg-offset-4">
    <form class="form-signin" role="form" method="post" action=".">
        {% csrf_token %}
        <h2 class="form-signin-heading">Create Account</h2> {{ signupForm.as_p }}
        <button class="btn btn-lg btn-primary btn-block" type="submit" value="Submit">Create</button>
    </form>
</div>
{% endblock %}